server.port: 8300

spring:
  application:
    name: order

  datasource:
    url: jdbc:postgresql://${E_COMMERCE_SERVICE_HOST}:5432/
    username: sushil
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.format_sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect

